version: 1
sequences:
  - protein:
      id: B
      sequence: EVQLLESGGGLIQPGGSLRLSCAASGLTVSNNYMNWVRQAPGKGLEWVSIIYSSGSTYYADSVKGRFTISRDTRKNTLYLQMHSLRVEDTAVYYCARERGWLDYWGQGTLVTVSS
  - protein:
      id: C
      sequence: VIWMTQSPSSLSASVGDRVTITCRASQSVSSHLNWYQQKPGKAPKLLIYAVSSLQSGVPSRFSGGDSGTDFTLTIASLQPEDFATYYCQQTYTIPRTFGQGTKVEIK
  - protein:
      id: D
      sequence: DSGCVVSWKNKELKCGSGIFITDNVHTWTEQYKFQPESPSKLASAIQKAHEEGICGIRSVTRLENLMWKQITPELNHILTENEVKLTIMTGDIKGIMQAGKRSLRPQPTELKYSWKAWGKAKMLSTELHNHTFLIDGPETAECPNTNRAWNSLEVEDYGFGVFTTNIWLKLKERQDVFCDSKLMSAAIKDNRAVHADMGYWIESALNDTWKIEKASFIEVKSCHWPKSHTLWSNGVLESEMIIPKNFAGPVSQHNYRPGYHTQTAGPWHLGRLEMDFDFCEGTTVVVTEDCGNRGPSLRTTTASGKLITEWCCRSCTLPPLRYRGEDGCWYGMEIRPLKEKEENLV
